### ISSUE TITLE
Question regarding multiGPU training

### ISSUE THREAD

**Issue by zzgg1** [gemengtju/SpEx_Plus#2]
Hi, I tried to use 8 GPU to train the model, however it seems only one GPU can be used. What I have changed is only "--gpus" id from default“0,1” to “0,1,2,3,4,5,6,7”. Except that, is there anything I should change? It seems like at beginning eval part, eight gpus can be used, but when it comes to train part, only one can be used.

**Comment by gemengtju** [comment]
you can use the multi-GPU training, you just modify the '--gpu' setting in 'train.sh' file from '0,1,2' to '0,1,2,3,4,5,6,7'. Thx.

**Comment by zzgg1** [comment]
Thanks for your reply, the reason is I used CUDA_LAUNCH_BLOCKING to debug.
